steps:
  # Debugging Step: List directories and check if Dockerfile is present
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'debug-ls'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Current directory:"
        pwd
        echo "Contents of current directory:"
        ls -la
        echo "Contents of container2 directory:"
        ls -la ./container2
  
  # Build Docker Image with a unique tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/cloud-assignment3-454119/cloud-a3/shadow1069/cloud-container2:$SHORT_SHA', './container2']

  # Push Docker Image to the registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/cloud-assignment3-454119/cloud-a3/shadow1069/cloud-container2:$SHORT_SHA']

  # Authenticate with Kubernetes cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'cloud-a3'
      - '--zone'
      - 'us-central1-c'
      - '--project'
      - 'cloud-assignment3-454119'

  # Apply Kubernetes deployment from YAML file
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/deployment.yaml']

  # Force the pods to restart with the new image (using the unique tag)
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/c2-deployment', 'container2=us-central1-docker.pkg.dev/cloud-assignment3-454119/cloud-a3/shadow1069/cloud-container2:$SHORT_SHA']

images:
  - 'us-central1-docker.pkg.dev/cloud-assignment3-454119/cloud-a3/shadow1069/cloud-container2:$SHORT_SHA'

options:
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cloud-a3'
  logging: CLOUD_LOGGING_ONLY
