steps:
  # Debugging Step
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'debug-ls'
    entrypoint: 'powershell'
    args:
      - '-Command'
      - |
        Write-Host "Current directory:"
        Get-Location
        Write-Host "Contents of current directory:"
        Get-ChildItem -Path . -Force
        Write-Host "Contents of container2 directory:"
        Get-ChildItem -Path ./container2 -Force
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/cloud-assignment3-454119/cloud-a3/shadow1069/cloud-container2', '.']

  - name: 'gce.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/cloud-assignment3-454119/cloud-a3/shadow1069/cloud-container2']

  # Authenticate with Kubernetes
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'cloud-a3'
      - '--zone'
      - 'us-central1-a'
      - '--project'
      - 'cloud-a3-454003'

  # Deploy to Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/deployment.yaml']

images:
  - 'us-central1-docker.pkg.dev/cloud-assignment3-454119/cloud-a3/shadow1069/cloud-container2'

options:
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cloud-a3'
  logging: CLOUD_LOGGING_ONLY