steps:
  # Debugging Step
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'debug-ls'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Current directory:"
        pwd
        echo "Contents of current directory:"
        ls -la
        echo "Contents of container2 directory:"
        ls -la ./container2
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/cloud-assignment3-454119/cloud-a3/shadow1069/cloud-container2', './container2']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/cloud-assignment3-454119/cloud-a3/shadow1069/cloud-container2']

  # Authenticate with Kubernetes
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'cloud-a3'
      - '--zone'
      - 'us-central1-c'
      - '--project'
      - 'cloud-assignment3-454119'

  # Deploy to Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/deployment.yaml']

images:
  - 'us-central1-docker.pkg.dev/cloud-assignment3-454119/cloud-a3/shadow1069/cloud-container2'

options:
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cloud-a3'
  logging: CLOUD_LOGGING_ONLY